-- AlterTable
ALTER TABLE "User" ADD COLUMN     "carbohydrateLimit" INTEGER DEFAULT 200,
ADD COLUMN     "fatLimit" INTEGER DEFAULT 90,
ADD COLUMN     "fiberLimit" INTEGER DEFAULT 40,
ADD COLUMN     "height" DOUBLE PRECISION,
ADD COLUMN     "informationFilled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "proteinLimit" INTEGER DEFAULT 80,
ADD COLUMN     "sodiumLimit" INTEGER DEFAULT 3000,
ADD COLUMN     "sugarLimit" INTEGER DEFAULT 60,
ADD COLUMN     "weight" DOUBLE PRECISION,
ALTER COLUMN "calorieLimit" SET DEFAULT 1600;
